version: '3.8'

services:
  db:
    image: postgres:15 # Versão estável e recente do PostgreSQL
    container_name: crm-azevix-db
    env_file:
      - ./.env # Carrega variáveis do .env para este serviço
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - crm_network

  backend:
    build: ./backend
    container_name: crm-azevix-backend
    env_file:
      - ./.env # Carrega variáveis do .env para este serviço
    environment:
      # Remova qualquer linha DATABASE_URL daqui, pois o app.py irá construí-la
      FLASK_ENV: production
    depends_on:
      - db # Garante que o banco de dados inicie antes do backend
    ports:
      - "5090:5090"
    volumes:
      - ./backend:/app
    networks:
      - crm_network

  nginx:
    image: nginx:alpine
    container_name: crm-azevix-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend # Garante que o backend inicie antes do nginx
    networks:
      - crm_network

volumes:
  postgres_data: # Volume para persistir os dados do PostgreSQL

networks:
  crm_network:
    driver: bridge
