version: '3.8'

services:
  db:
    image: postgres:15
    container_name: crm-azevix-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: crm-azevix-backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5090:5090"
    networks:
      - crm_network

  nginx:
    image: nginx:alpine
    container_name: crm-azevix-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # --- LINHA CRUCIAL ADICIONADA DE VOLTA ---
      # Mapeia a pasta estática local para dentro do contêiner Nginx
      - ./backend/static:/usr/share/nginx/html/static
    depends_on:
      - backend
    networks:
      - crm_network

volumes:
  postgres_data:

networks:
  crm_network:
    driver: bridge